main().catch(err => console.log('Error: ', err));

async function main() {
   console.log('TODO');
}
